config/routes.rb
Rails.application.routes.draw do
  root "departments#index"
  
    resources :departments do
      resources :items
    end
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]


  def index
    @department = Department.all
  end

  def show

  end


  def update
    if @department.update(department_params)
      redirect_to department_path(@department)
    else
      render :edit
    end
  end


  def edit
    render partial: 'form'
  end


  def new
    @department = Department.new
    render partial: 'form'
  end

  def create
    @department = Department.new(department_params)

      if @department.save
        redirect_to departments_path
      else
        render :new
      end
  end


  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private
    def department_params
      params.require(:department).permit(:name)
    end

    def set_department
      @department = Department.find(params[:id])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]
 
  def index
    @items = @department.items 
  end

  def show
  end

  def new
    @items = @department.items.new
    render partial: "form"
  end

  def create
    @items = @department.items.new(item_params)

    if @items.save
      redirect_to department_items_path(@department)
    else
      render :new
    end
  end


  def update

    if @items.update(item_params)
      redirect_to department_item_path(@department, @items)
    else
      render :edit
    end
  end


  def edit
    render partial: 'form'
  end



  def destroy

    @items.destroy
    redirect_to department_items_path(@department)
  end



  private 
  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_item
    @items = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1> <%= @department.id ? "Edit Department" : "New Department" %> </h1>

<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<%end%>

app/views/departments/edit.html.erb
<h1> Edit Department </h1>

app/views/departments/index.html.erb
<h1> Choose A Department </h1>

<%= link_to "Create a New Department", new_department_path %>

<%= @department.length === 0 ? "No Departments Added" : "" %>
<ul>
  <% @department.each do |department| %>
    <li> <%= link_to department.name, department_path(department) %> </li>
    <% end %>

app/views/departments/new.html.erb
<h1> New Store </h1>

app/views/departments/show.html.erb
<h1><%= @department.name %> 

<p> What would you like to do? </p>

<%= link_to 'View Items', department_items_path(@department) %>
<br />
<%= link_to "Edit Department", edit_department_path(@department) %>
<br />
<%= link_to "Delete Department", department_path(@department), method: :delete%>

app/views/items/_form.html.erb
<h1><%= @items.id ? 'Edit Item' : 'Create Item' %></h1>

<hr />
<%= form_for [@department, @items] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :price %>
  <%= f.number_field :price, required: true %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back to menu', department_items_path %>

app/views/items/edit.html.erb
<h1> Edit Item </h1>

app/views/items/index.html.erb
<h1>Click an item to view </h1>

<%= link_to 'Create a new Item', new_department_item_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@department, item] %></li>
  <% end %>
  
</ul>

<%= link_to 'Back to menu', departments_path %>

app/views/items/new.html.erb
<h1> Add New Item </h1>

app/views/items/show.html.erb
<h1><%= @items.name %></h1>
<h3><%= @items.price %></h3>

<hr />


<%= link_to 'New Item', new_department_item_path %>
<%= link_to 'Edit Item', edit_department_item_path(@department) %>
<%= link_to 'Delete Item', department_item_path, method: :delete %>
<%= link_to 'Back To Main', departments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>